image: docker.repo.russianpost.ru/python:3.8-slim-buster
stages:
  - test
test:
  when: manual
  before_script:
    - echo "deb http://nexus.repo.russianpost.ru/deb/repository/buster/ buster main" > /etc/apt/sources.list
    - apt-get update -y > /dev/null
    - apt-get install curl -y
    - curl -k -L http://cert.tools.russianpost.ru/Russian-post-RootCA.crt -o /usr/local/share/ca-certificates/Russian-post-RootCA.crt
    - update-ca-certificates --fresh > /dev/null
    - export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
    - pip config set global.index-url https://pypi.repo.russianpost.ru/simple/
    - pip install --upgrade pip pipenv
    - apt-get install -y iputils-ping
  cache:
    paths:
      - $PIP_CACHE_DIR
      - $PIPENV_CACHE_DIR
  variables:
    PYTHONPATH: $CI_PROJECT_DIR
    PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip
    PIPENV_CACHE_DIR: $CI_PROJECT_DIR/.cache/pipenv
    BROWSER: chrome
  artifacts:
    when: always
    expire_in: 30min
    paths:
      - report.html
      - report.xml
      - allure-results/
    reports:
      junit: report.xml
  tags:
    - inet-docker
  script:
    - pipenv lock
    - pipenv sync --clear
    - pipenv run pytest  --junitxml=report.xml --html=report.html --self-contained-html --browser=$BROWSER --local='false' --alluredir=./allure-results
    - pipenv --rm
  services:
    - selenium/standalone-chrome
  only:
    variables:
      - $BROWSER == 'chrome'




